/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import CONTROL.ProdutosControl;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author SYSTEM N.P
 */
public class PCadastraProdutos extends javax.swing.JPanel {

    private static ProdutosControl produto;

    /**
     * Creates new form CadastraProdutos
     */
    public PCadastraProdutos() {
        initComponents();
        this.produto = new ProdutosControl();

    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            BufferedImage imagem = ImageIO.read(getClass().getResource("/RESOURCES/pcadastroprodutos.PNG"));//por o nome da tela que vai estar em resouce
            
            
            
            g.drawImage(imagem, 0, 0, this);
            
            

        } catch (IOException ex) {
            System.err.println("arquivo não existe no resource");
        
            }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jFormattedTextField2.setText("jFormattedTextField2");

        setPreferredSize(new java.awt.Dimension(768, 432));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Registrar Produto:");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 331, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 51, 51));
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 331, -1));

        jTextField3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 51, 51));
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 331, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 51, 51));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 331, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(51, 102, 255));
        jButton3.setText("limpar colunas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            produto.cadastraProdutos(jTextField1.getText(), Double.parseDouble(jTextField2.getText()), produto.pegaultimocodigoProdutos(), Integer.parseInt(jTextField4.getText()), jTextField3.getText());

        } catch (java.lang.NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para que o produto seja cadastrado", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Frame.trocaPainel("painelADM", new PAdmin());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");  
       jTextField4.setText("");
           
           
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
