/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VIEW;

import CONTROL.CarrinhoControl;
import CONTROL.ClienteControl;
import CONTROL.ProdutosControl;
import MODEL.Carrinho;
import MODEL.Produtos;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author 0068952
 */
public class PPedidos extends javax.swing.JPanel {

    private DefaultListModel<Produtos> dadosListaModel1 = new DefaultListModel<Produtos>();
    public static DefaultListModel<Carrinho> dadosListaModel2 = new DefaultListModel<Carrinho>();

    private static ArrayList<Produtos> produtocardapio = new ArrayList<>();
    private static ArrayList<Carrinho> produtocarrinho = new ArrayList<>();

    private static ClienteControl cliente = new ClienteControl();

    private static ProdutosControl produto;
    private static CarrinhoControl carrinho;

    /**
     * Creates new form PPedidos
     */
    public PPedidos() {
        initComponents();

        minhasConfiguracoesUI();

        jTextArea2.setEditable(false);

        telabk();
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        try {
            BufferedImage imagem = ImageIO.read(getClass().getResource("/RESOURCES/telapedidos.PNG"));//por o nome da tela que vai estar em resouce

            g.drawImage(imagem, 0, 0, this);

        } catch (IOException ex) {
            System.err.println("arquivo não existe no resource");
        }
    }

    public DefaultListModel pegaCarrinho() {

        return dadosListaModel2;

    }

    private void minhasConfiguracoesUI() {
        this.dadosListaModel1 = new DefaultListModel<>();

        this.jList1.setModel(this.dadosListaModel1);

        this.dadosListaModel2 = new DefaultListModel<>();

        this.jList3.setModel(this.dadosListaModel2);

        this.produto = new ProdutosControl();

        this.carrinho = new CarrinhoControl();

    }

    public void telabk() {

        SwingWorker atualizadorPontos = new SwingWorker() {

            @Override
            protected Object doInBackground() throws Exception {

                while (true) {

                    dadosListaModel1.addAll(produto.pegaProdutos());
                    Thread.sleep(10000);

                    dadosListaModel1.clear();

                }
            }

        };

        atualizadorPontos.execute();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(51, 102, 255));
        jButton6.setText("Ver descrição do produto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(51, 102, 255));
        jButton4.setText("Finalizar compra");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, -1));

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 51, 51));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 400, 230));

        jList1.setBackground(new java.awt.Color(51, 51, 51));
        jList1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 51, 51));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 100, 400, 230));

        jList3.setBackground(new java.awt.Color(51, 51, 51));
        jList3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jList3.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane4.setViewportView(jList3);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 390, 210));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Digite os produtos desejados:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("Retirar uma unidade de produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 720, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 240, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(51, 102, 255));
        jButton3.setText("Retirar um produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Valor:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("R$ 0.00");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 80, 20));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(51, 102, 255));
        jButton5.setText("Adicionar ao carrinho");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
            Produtos produtoselecionado = jList1.getSelectedValue();

            ProdutosControl PC = new ProdutosControl();

            jTextArea2.setText(PC.mostradesc(produtoselecionado.getCodigo()));

        } catch (java.lang.NullPointerException ex) {

            JOptionPane.showMessageDialog(null, "Selecione algum produto do cardapio para ver sua descrição", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int r = JOptionPane.showConfirmDialog(null, "Você tem ceteza que já terminou a compra?", "Confirmação de compra", JOptionPane.YES_NO_OPTION);
        if (r == JOptionPane.YES_OPTION) {

            if (carrinho.guardaCarriho(dadosListaModel2) == true) {
                Frame.trocaPainel("painelFinal", new Pfinal());
            } else {

                JOptionPane.showMessageDialog(null, "É necessário informar produtos para que a compra possa ser realizada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            carrinho.guardaCarriho(dadosListaModel2);
            jLabel5.setText("R$" + carrinho.totalcarrinho());

            int x = jList3.getSelectedIndex();
            Produtos produtoselecionado = jList3.getSelectedValue().getProduto();

            CarrinhoControl CC = new CarrinhoControl();

            dadosListaModel2 = CC.retiraumprodutocarrinho(x, dadosListaModel2, jList3, produtoselecionado);

            carrinho.guardaCarriho(dadosListaModel2);
            jLabel5.setText("R$" + carrinho.totalcarrinho());

        } catch (java.lang.NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Selecione algum produto do carrinho para que uma unidade dele seja retirada do carrinho", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            int x = jList3.getSelectedIndex();

            int quantdevolvida = jList3.getSelectedValue().getQuantCarrinho();

            CarrinhoControl CC = new CarrinhoControl();

            Produtos produtoselecionado = jList3.getSelectedValue().getProduto();

            dadosListaModel2 = CC.deletaprodutocarrinho(x, dadosListaModel2, produtoselecionado, quantdevolvida);

            carrinho.guardaCarriho(dadosListaModel2);
            jLabel5.setText("R$" + carrinho.totalcarrinho());

            jList3.updateUI();

            produtocarrinho.clear();
            for (int a = 0; a < dadosListaModel2.size(); a++) {
                produtocarrinho.add(dadosListaModel2.getElementAt(a));

            }

        } catch (java.lang.NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Selecione algum produto do carrinho para que ele retirado do carrinho", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       try {
            int codigoproduto = Integer.parseInt(jTextField1.getText());
            if (produto.verificacodigo(codigoproduto) == true) {

                dadosListaModel2.clear();
                dadosListaModel2.addAll(carrinho.atualizacarinho(codigoproduto, jList1, produtocarrinho, jList3));

                produtocarrinho.clear();
                for (int a = 0; a < dadosListaModel2.size(); a++) {
                    produtocarrinho.add(dadosListaModel2.getElementAt(a));

                }

                carrinho.guardaCarriho(dadosListaModel2);
                jLabel5.setText("R$" + carrinho.totalcarrinho());

                jList3.updateUI();
            }
        } catch (java.lang.NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Informe o código do produto para adicioná-lo ao carrinho", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JList<Produtos> jList1;
    private javax.swing.JList<Carrinho> jList3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
